apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spike-poc-argo-application-2
  namespace: argocd
spec:
  project: default

  source:
    # repoURL: https://github.com/parthbhope-kd/argocd-poc.git
    # targetRevision: HEAD
    # path: dev
    source:
    path: apps
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: spike-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 

    automated: # polls from the Git repo every 3 mins by default
      selfHeal: true # by default changes made to the cluster manually will not trigger sync, adding selfHeal enables auto sync
      prune: true 