apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-app-3
spec:
  selector:
    matchLabels:
      app: spike-app-3
  replicas: 1
  template:
    metadata:
      labels:
        app: spike-app-3
    spec:
      containers:
      - name: spike-app-3
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
