apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-app-2
spec:
  selector:
    matchLabels:
      app: spike-app-2
  replicas: 1
  template:
    metadata:
      labels:
        app: spike-app-2
    spec:
      containers:
      - name: spike-app-2
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
